### ISSUE TITLE
[EPIC] migrate versionMetadata.xml to the database for all objects

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#3076]
- [ ] Create a data model for storing a version history in the database (using the existing VersionLog model: https://github.com/sul-dlss/dor-services-app/blob/main/openapi.yml#L3004)
- [ ] Copy data from all objects versionMetadata.xml into the database
- [ ] Disable the legacy datastream update for versionMetadata in argo
- [ ] Disable the legacy datastream update https://github.com/sul-dlss/dor-services-app/blob/e8d7595f96c62b8b4a7c13a98618c2c66a521504/app/controllers/metadata_controller.rb#L39
- [ ]Refactor VersionsService to use the new data model
- [ ]Find all uses of Dor::Item#current_version and replace with a database query.
