### ISSUE TITLE
EPIC: Preservation maintenance

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/dor-services-app#4258]
### Data Commons Workcycle Q4 2022
- [x] finish removing preservation policies table and logic (sul-dlss/preservation_catalog#1961, sul-dlss/preservation_catalog#1967)
- [x] finish replacing resque with sidekiq (sul-dlss/preservation_catalog#1888, sul-dlss/preservation_catalog#1984)
- [x] finish robots bag transfer by file system copy (sul-dlss/preservation_robots#445)
- [x] finish disentangling stage and qa storage roots (sul-dlss/preservation_catalog#1986)
- [x] dashboard:  one or two iterations of improvements
- [ ] refactors to lower cognitive load
<hr/>

- [x] documentation:  
   - [x] getting started with prescat (sul-dlss/preservation_catalog#1971)
   - [x] audit checks and validaton (sul-dlss/preservation_catalog#2010)
   - [x] diagram overall architecture (sul-dlss/preservation_catalog#1959)
- [x] replication restructure (sul-dlss/preservation_catalog#2007)

**Comment by ndushay** [comment]
I am closing this preservation maintainance EPIC from Q4 2022.
