### ISSUE TITLE
DSA Folio Cutover checklist

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#4546]
Libsys will run their last (daily?) pickup of SDR purls to put in Symphony  MARC records on  Fri 8/18 4:45am
The shared mount where the file(s) with the 856s get placed will remain available after that point.

- Andrew wants any "release to SW" requests to go into the file that the Symphony script WOULD pick up.
   - With _the Argo release to SW feature turned off_, there will still be one route to SW release: when something is added to a collection that’s set to auto-release new items.  Andrew says he's "fine with going through the 856 file and following up myself post-launch."

## Before Symphony is off
- [x] #4549 Goobi processing is prepared for the change
- [x] #4550 ObjectsController error message

## Symphony becomes Read Only (After ? 5pm on Fri August 18 ?)
- [ ] ensure that file for Symphony 856 updates is there and writable

## FOLIO Goes Live!  (? Monday, August 28 ?):
- [x] #4570
- [x] #4568
- [x] #4569 (Andrew)

 
## After Confirmation that All is Working Appropriately with Folio
- [x] #4548 
- [x] #4438 
- [x] #4595
- [ ] #4572 (much later)

**Comment by ndushay** [comment]
this is done done.  And done done done.
