### ISSUE TITLE
when available, upgrade preservation-client

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dor-services-app#573]
once https://github.com/sul-dlss/preservation-client/pull/29 is merged and a new version has been cut:
- [x] update the preservation-client gem (PR #576)
- [x] add an example token setting in settings.yml (PR #576)
- [x] update the [`Preservation::Client.configure` call](https://github.com/sul-dlss/dor-services-app/blob/0301e4aa7049550bc4cb988c39f3166bebcd7a75/config/initializers/preservation_client.rb#L4) to use the new setting (PR #576)
- [x] mint real tokens on stage and prod pres cat servers, and add those token values as corresponding overrides in the stage and prod shared configs settings (PRs sul-dlss/shared_configs/pull/1172, sul-dlss/shared_configs/pull/1174)

**Comment by jmartin-sul** [comment]
see also https://github.com/sul-dlss/preservation_catalog/pull/1306 and https://github.com/sul-dlss/preservation_catalog/issues/1298
