### ISSUE TITLE
[ÜBER] Create an endpoint for assembly to support reaccessioning

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services-app#702]
This can be used by pre-assembly/lyberservices-scripts and Goobi (after it supports token header)

Fixes sul-dlss/argo#1781

Steps to take, in order:

- [x] update dor-services-app to add a new endpoint (sul-dlss/dor-services-app#703)
- [x] update dor-services-client to expose this endpoint (sul-dlss/dor-services-client#147)
- [x] cut new release of dor-services-client
- [x] update lybservices-scripts to use this new endpoint via dor-services-client (sul-dlss/lyberservices-scripts#59)
- [x] update pre-assembly to use this new endpoint via dor-services-client (sul-dlss/pre-assembly#622 (in a branch now, ready for testing in #739)
- [x] test new object and existing object accessioning with both pre-assembly ~~and lybservices-scripts~~
- [x] coordinate with Goobi to get their changes done (#745 and sul-dlss/sul-goobi#258)

Background, relevant code from pre-assembly:
```ruby
      create_new_version if openable?
      initialize_assembly_workflow

    # Call web service to add assemblyWF to the object in DOR.
    def initialize_assembly_workflow
      workflow_client.create_workflow_by_name(druid.druid, 'assemblyWF', version: current_object_version)
    end

    def workflow_client
      logger = Logger.new(Settings.workflow.logfile, Settings.workflow.shift_age)
      Dor::Workflow::Client.new(url: Settings.workflow_url, logger: logger, timeout: Settings.workflow.timeout)
    end

    def openable?
      version_client.openable?
    end

    def object_client
      @object_client ||= Dor::Services::Client.object(druid.druid)
    end

    def version_client
      object_client.version
    end

    # When reaccessioning, we need to first open and close a version without kicking off accessionWF
    def create_new_version
      version_client.open(
        significance: 'major',
        description: 'pre-assembly re-accession',
        opening_user_name: bundle.bundle_context.user.sunet_id
      )
      version_client.close(start_accession: false)
    end
```
