### ISSUE TITLE
Checklist for Fedora/DSA/hydra_etd migration

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/dor-services-app#851]
## DEVS FRIDAY BEFORE

- [ ] cathy provides etd we can see in hydra_etd app  (`dn185rf0270`)

### Alert Ops to Silence Nagios Alerts

? track which ones turned off so they can be turned on again?

### Shut Down Google Books Accessioning

- [x]  https://sul-gbooks-[stage|prod].stanford.edu/features

### Shut Down Robot Workers

shut off the workers manually by killing (only) the resque-pool-master process (hotswap interferes with other cap resque commands)

https://robot-console-prod.stanford.edu/overview will be helpful.

```
 from the git repo on your laptop:
$ bundle exec cap prod ssh

# once you're on the preservation-robots1-prod server:
$ ps -eaf | grep resque
# look for line like this:
# pres      1234     1  0 Feb18 ?        00:00:15 resque-pool-master[20200218172434]: managing [10204, 10207, 10210, 10214, 10219, 10223, 10228, 10235, 10239, 10242]
$ kill -s QUIT [nnn] # substitute the appropriate resque-pool-master pid, obviously
$ ps -eaf | grep resque # confirm the workers aren't running
$ exit # get out of super user mode
```

- [x] gis-robot-suite   `kurma-robots1-prod`  per above - and make sure workers are down
- [x] was_robot_suite  `was-robots1-prod`  per above - and make sure workers are down
- [x] preservation_robots `preservation-robots1-prod` per above - and make sure workers are down
- [x] common-accessioning  (each of: 5 prod VMs, 2 stage VMs) - and make sure workers are down
- [x] confirm there are no workers working https://robot-console-prod.stanford.edu/overview

### OPS Shuts Down Applications

NOTE:  puppet will restart passenger so we need ops to shut passenger down on all the VMs for these apps.

- [x] argo (2 VMs) - Argo has the registration form and also users can update xml datastreams directly.
- [x] hydrus - directly accesses fedora
- [x] hydra_etd - directly accesses fedora
- [x] was-registrar-app - registers objects via dor-services-app
- [x] preassembly - looks up objects in fedora via dsa

Last:

- [x] sdr-api

### dor-services-app Database Contents

Get counts of dor-services-app db objects via dor-services-app rails console

- [x] AdministrativeTag.count  _____________
- [x] BackgroundJobResult.count  _____________
- [x] Event.count  _____________

### Fedora Contents

```
cd /data/fedora
ls -laR {datastream,object}Store > ~/fedora_data_snapshot_BEFORE_MIGRATION.txt
# then scp file to laptop
```

## OPS Migration

- sul-dor-prod (fedora) VM will be updated 
  - shut down tomcat
  - do final backups
  - ...
- dor-services-app VM will be updated
- hydra_etd VM will be updated

### Confirm Fedora Contents

- [x] Confirm against previous contents:
```
cd /data/fedora
ls -laR {datastream,object}Store > ~/fedora_data_snapshot_AFTER_MIGRATION.txt
# then scp file to laptop
diff ~/fedora_data_snapshot_BEFORE_MIGRATION.txt ~/fedora_data_snapshot_AFTER_MIGRATION.txt
```
- [x]  check http://sul-dor.stanford.edu/fedora/objects
- [ ] check http://sul-dor.stanford.edu/fedora/risearch

#### Deploy dor-services-app on Updated VM

- [x] shared_configs come over and are using the right branch
- [x] https://dor-services-prod.stanford.edu/status/all
- [x] https://dor-services-prod.stanford.edu/queues/ 
- [x] rails console

#### Confirm dor-services-app Database Contents

- [x] AdministrativeTag.count  _____________
- [x] BackgroundJobResult.count  _____________
- [x] Event.count  _____________
- [x] confirm against previous contents

### Restart Applications

We need Ops to reverse its puppet magic for these apps.

First:
- [x] sdr-api
Then:
- [x] argo - Argo has the registration form and also users can update xml datastreams directly.
- [x] hydrus - directly accesses fedora
- [x] hydra_etd - directly accesses fedora
- [x] was-registrar-app - registers objects via dor-services-app
- [x] preassembly - looks up objects in fedora via dsa

### Restart Robot Workers

```
 from the git repo on your laptop:
$ bundle exec cap resque:pool:hot_swap
```

- [x] common-accessioning  (each of: 5 prod VMs, 2 stage VMs) - and make sure workers are up
- [x] preservation_robots `preservation-robots1-prod` per above - and make sure workers are up
- [x] gis-robot-suite   `kurma-robots1-prod`  per above - and make sure workers are up
- [x] was_robot_suite  `was-robots1-prod`  per above - and make sure workers are up
- [x] confirm there are workers https://robot-console-prod.stanford.edu/workers

### Use Argo to confirm everything
- [x] Argo can get foxml for object
- [x] Update an existing object in Argo and confirm it runs through all the robots ok.

### Deploy hydra_etd on Updated VM

- [x] shared_configs come over and are using the right branch
- [x] https://sul-hydra-etd-prod.stanford.edu/status/all
- [x] https://sul-hydra-etd-prod.stanford.edu/queues 
- [x] rails console
- [ ] can see druid from above (`dn185rf0270` ?)
- [ ] Cathy says it looks ok

### Restart Google Books Accessioning

- [ ]  https://sul-gbooks-[stage|prod].stanford.edu/features

## DEVS Watch Honeybadger For Errors

**Comment by ndushay** [comment]
closing this as the migration is done.
